name: 'Install Kustomize Action'
description: 'Installs Kustomize (Default v5.4.1)'
inputs:
  version:
    description: "Kustomize version to be installed"
    required: false
    default: 5.4.1
  condition:
    description: "Kustomize version to be installed"
    required: false
runs:
  using: "composite"
  steps:
    - id: create-and-process-tag-value
      run: |
          wget -qO-  https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv${{ inputs.version }}/kustomize_v${{ inputs.version }}_linux_amd64.tar.gz | tar -xvzf - && sudo mv kustomize /usr/local/bin/
      shell: bash
    - id: condition
      shell: bash
      env:
          REPO_NAME: "hii"
      run: |
        touch created.yaml
        echo "hiiiii" > created.yaml
        env

    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    
    - name: ls
      run: ls
      shell: bash

    - name: Run goodbye.sh
      run: temp.sh
      shell: bash
