name: 'Install Multiple Tools Action'
description: 'Installs multiple tools'
outputs:
  file_path:
    description: "Random number"
    value: ${{ steps.file_path.outputs.file_path }}
runs:
  using: "composite"
  steps:
    - name: Install Tools
      run: |
        echo "this is created by action" >> actions_created.yaml
      shell: bash
    - name: Give file path
      id: file_path
      run: |
        file_path="actions_created.yaml"
        cat fileinworkflow.txt
        echo "File Path set to: $file_path"
        echo "file_path=actions_created.yaml" >> $GITHUB_OUTPUT
        echo ""
        echo "github.action_path=${{ github.action_path }}"
        echo "GITHUB_WORKSPACE=${GITHUB_WORKSPACE}"
        echo "GITHUB_ACTION_PATH=${GITHUB_ACTION_PATH}"
        echo "GITHUB_PATH=$GITHUB_PATH"
        pwd
      shell: bash
    - name: install ridectl
      id: ridectl
      shell: bash
      run: |
        curl -L "https://github.com/Ridecell/ridectl/releases/download/v0.3.2-alpha.1/ridectl_linux.zip" -o ./ridectl_linux.zip
        unzip ridectl_linux.zip && cp ridectl ${{ github.action_path }}
        echo "${{ github.action_path }}" >> $GITHUB_PATH
