name: 'Image tag'
description: 'Create image tag and value'
inputs:
  images:
    description: 'The image repository name.'
    required: false
outputs:
  tag:
    description: "Tag string"
    value: ${{ steps.image-tag-value.outputs.tag }}
  version:
    description: "Tag value"
    value: ${{ steps.image-tag-value.outputs.version }}
runs:
  using: "composite"
  steps:
    - id: create-and-process-tag-value
      run: |
        TAG=${{ github.ref_name }}
        TAG=$(echo "${TAG}" | sed -E -e 's/[^a-zA-Z0-9-]/-/g' -e 's/-+/-/g' -e 's/[-]*$//g')
        TAG=${TAG:0:40}
        echo "TAG=$TAG" >> $GITHUB_ENV
      shell: bash
    - id: docker-meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ inputs.images }}
        tags: |
          type=raw,value={{date 'X'}}-{{sha}}-${{ env.TAG }}
    - id: image-tag-value
      run: |
        echo "version=${{ steps.docker-meta.outputs.version }}" >> $GITHUB_OUTPUT
        echo "tag=${{ steps.docker-meta.outputs.tags }}" >> $GITHUB_OUTPUT
      shell: bash