name: 'Install Dependencies Action'
description: 'Installs Dependencies'
inputs:
  tool:
    description: 'Tool to install'
    required: true
  version:
    description: "Version to be installed"
    required: false
runs:
  using: "composite"
  steps:
    - name: Install Kustomize
      if: ${{ inputs.tool == 'kustomize' }} 
      shell: bash
      id: install-kustomize
      run: |
        version="${{ inputs.version || '5.4.1' }}"
        wget -qO /tmp/kustomize.tar.gz "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv${{ version }}/kustomize_v${{ version }}_linux_amd64.tar.gz"
        if [ $? -ne 0 ]; then
          echo "Failed to download kustomize."
          exit 1
        fi
        tar -xvzf /tmp/kustomize.tar.gz -C /tmp/
        if [ $? -ne 0 ]; then
          echo "Failed to extract kustomize."
          exit 1
        fi
        sudo mv /tmp/kustomize /usr/local/bin/

    - name: Install gh
      if: ${{ inputs.tool == 'gh' }}
      shell: bash
      id: install-gh
      run: |
        version="${{ inputs.version || '2.47.0' }}"
        arch=$(uname -m)
        wget -qO /tmp/gh.deb https://github.com/cli/cli/releases/download/v$version/gh_$version_linux_$arch.deb
        if [ $? -ne 0 ]; then
          echo "Failed to download gh."
          exit 1
        fi
        sudo dpkg -i /tmp/gh.deb
        if [ $? -ne 0 ]; then
          echo "Failed to install gh."
          exit 1
        fi
