name: 'Install Dependencies Action'
description: 'Installs Dependencies'
inputs:
  tool:
    description: 'Tool to install'
    required: true
  version:
    description: "Version to be installed"
    required: false
runs:
  using: "composite"
  steps:
    - name: Install Kustomize
      if: ${{ inputs.tool == 'kustomize' }} 
      shell: bash
      id: install-kustomize
      run: |
        version="${{ inputs.version:-5.4.1 }}"
        wget -qO- "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv$version/kustomize_v$version_linux_amd64.tar.gz" | tar -xvzf - && sudo mv kustomize /usr/local/bin/

    - name: Install gh
      if: ${{ inputs.tool == 'gh' }}
      shell: bash
      id: install-gh
      run: |
        version="${{ inputs.version:-2.47.0 }}"
        arch=$(uname -m)
        mkdir -p -m 755 /etc/apt/keyrings && wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
        && chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
        && echo "deb [arch=$arch signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
        && apt update \
        && apt install gh="$version" -y
