name: 'Install Multiple Tools Action'
description: 'Installs multiple tools'
outputs:
  file_path:
    description: "Random number"
    value: ${{ steps.file_path.outputs.file_path }}
runs:
  using: "composite"
  steps:
    - name: Install Tools
      run: |
        echo "this is created by action" >> actions_created.yaml
      shell: bash
    - name: Give file path
      id: file_path
      run: |
        file_path="actions_created.yaml"
        cat fileinworkflow.txt
        echo "File Path set to: $file_path"
        echo "file_path=actions_created.yaml" >> $GITHUB_OUTPUT
      shell: bash
