name: 'Install Multiple Tools Action'
description: 'Installs multiple tools'
inputs:
  tools:
    description: 'List of tools to install with versions'
    required: true
    default: ""
runs:
  using: "composite"
  steps:
    - name: Install Tools
      run: |
        echo "this is created by action" >> actions_created.yaml
      shell: bash
