name: 'Install Dependencies Action'
description: 'Installs Dependencies'
inputs:
  tool:
    description: 'Tool to install'
    required: true
  version:
    description: "Version to be installed"
    required: false
runs:
  using: "composite"
  steps:
    - name: Install Kustomize
      if: ${{ inputs.tool == 'kustomize' }} 
      shell: bash
      id: install-kustomize
      run: |
        version="${{ inputs.version }}"
        if [ -z "$version" ]; then
          echo "No input version provided. Using default version 5.4.1."
          version="5.4.1"
        fi
        wget -qO /tmp/kustomize.tar.gz "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv${version}/kustomize_v${version}_linux_amd64.tar.gz"
        if [ $? -ne 0 ]; then
          echo "Failed to download kustomize."
          exit 1
        fi
        tar -xvzf /tmp/kustomize.tar.gz -C /tmp/
        if [ $? -ne 0 ]; then
          echo "Failed to extract kustomize."
          exit 1
        fi
        sudo mv /tmp/kustomize /usr/local/bin/

    - name: Install gh
      if: ${{ inputs.tool == 'gh' }}
      shell: bash
      id: install-gh
      run: |
        version="${{ inputs.version }}"
        if [ -z "$version" ]; then
          echo "No input version provided. Using default version 2.47.0."
          version="2.47.0"
        fi
        sudo mkdir -p -m 755 /etc/apt/keyrings && wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
        && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
        && sudo echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
        && sudo apt update \
        && sudo apt install gh=${version} -y
        if [ $? -ne 0 ]; then
          echo "Failed to install gh."
          exit 1
        fi