name: 'Resource Limit Check'
description: 'Check resource limits in YAML manifests'
inputs:
  file:  
    description: 'Path to YAML file to check'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.file }}