name: 'Install Multiple Tools Action'
description: 'Installs multiple tools'
outputs:
  file-path:
    description: "Random number"
    value: ${{ steps.filepath-generator.outputs.file-path }}
runs:
  using: "composite"
  steps:
    - name: Install Tools
      run: |
        echo "this is created by action" >> actions_created.yaml
      shell: bash
    - name: Give file path
      id: file-path
      run: |
        file_path="actions_created.yaml"
        echo "file-path=$file_path >> $GITHUB_OUTPUT
      shell: bash
