name: 'Image tag'
description: 'Create image tag and value'
inputs:
  version:
    description: "Tag string"
    required: false
    default: 5.4.1
runs:
  using: "composite"
  steps:
    - id: create-and-process-tag-value
      run: |
          wget -qO-  https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv${{ inputs.version }}/kustomize_v${{ inputs.version }}_linux_amd64.tar.gz | tar -xvzf - && sudo mv kustomize /usr/local/bin/
      shell: bash
    