name: 'Image tag'
description: 'Greet someone'
inputs:
  commit-id:
    description: 'The commit ID.'
    required: true
  branch-name:
    description: 'The branch name.'
    required: true
  tag-name:
    description: 'The tag name.'
    required: false
  images:
    description: 'The image name.'
    required: true
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
  image-tag:
    description: "Processed tag string"
    value: ${{ steps.image-tag.outputs.IMAGE_TAG_VALUE }}
runs:
  using: "composite"
  steps:
    - id: short-commit-id
      run: |
        SHORT_SHA=${{ inputs.commit-id }}
        echo "SHORT_SHA=${SHORT_SHA::7}" >> $GITHUB_ENV
      shell: bash
    - id: current-date
      run: |
        echo "CURRENT_DATE=$(date +'%s')" >> $GITHUB_ENV
      shell: bash
    - id: create-and-process-tag-value
      run: |
        IMAGE_TAG_VALUE=${{ env.CURRENT_DATE }}-${{ env.SHORT_SHA }}-${{ inputs.branch-name }}
        IMAGE_TAG_VALUE=${IMAGE_TAG_VALUE:0:63}
        IMAGE_TAG_VALUE=$(echo "${IMAGE_TAG_VALUE}" | sed -E -e 's/-+/-/g' -e 's/_+/_/g' -e 's/[^[:alnum:]]*$//' | tr -d '\@\#\$\%\^\&\*\(\)\{\}\[\]')
        echo "IMAGE_TAG_VALUE=$IMAGE_TAG_VALUE"
        echo "IMAGE_TAG_VALUE=$IMAGE_TAG_VALUE" >> $GITHUB_ENV
      shell: bash
    - id: image-tag
      run: |
        IMAGE_TAG_VALUE=${{ inputs.images }}${{ env.IMAGE_TAG_VALUE }}
        echo "IMAGE_TAG_VALUE=$IMAGE_TAG_VALUE" >> $GITHUB_OUTPUT
      shell: bash
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: goodbye.sh
      shell: bash
