name: 'Image tag'
description: 'Greet someone'
inputs:
  commit-id:
    description: 'The commit ID.'
    required: false
  branch-name:
    description: 'The branch name.'
    required: false
  tag-name:
    description: 'The tag name.'
    required: false
  images:
    description: 'The image name.'
    required: false
outputs:
  image-tag:
    description: "Tag string"
    value: ${{ steps.image-tag.outputs.IMAGE_TAG }}
  image-tag-value:
    description: "Tag value"
    value: ${{ steps.image-tag.outputs.IMAGE_TAG_VALUE }}
runs:
  using: "composite"
  steps:
    - id: short-commit-id
      run: |
        SHORT_SHA=${{ github.sha }}
        echo "SHORT_SHA=${SHORT_SHA::7}" >> $GITHUB_ENV
      shell: bash
    - id: current-date
      run: |
        echo "CURRENT_DATE=$(date +'%s')" >> $GITHUB_ENV
      shell: bash
    - id: create-and-process-tag-value
      run: |
        TAG=${{ env.CURRENT_DATE }}-${{ env.SHORT_SHA }}-${{ github.ref_name }}
        TAG=${TAG:0:63}
        TAG=$(echo "${TAG}" | sed -E -e 's/-+/-/g' -e 's/_+/_/g' -e 's/[^[:alnum:]]*$//' | tr -d '\@\#\$\%\^\&\*\(\)\{\}\[\]')
        echo "TAG=$TAG"
        echo "TAG=$TAG" >> $GITHUB_ENV
      shell: bash
    - id: image-tag-value
      run: |
        IMAGE_TAG_VALUE=${{ env.TAG }}
        echo "IMAGE_TAG_VALUE=$IMAGE_TAG_VALUE" >> $GITHUB_OUTPUT
      shell: bash
    - id: image-tag
      run: |
        IMAGE_TAG=${{ inputs.images }}:${{ env.TAG }}
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT
      shell: bash
