name: 'Install Multiple Tools Action'
description: 'Installs multiple tools'
inputs:
  tools:
    description: 'List of tools to install with versions'
    required: true
    default: ""
runs:
  using: "composite"
  steps:
    - name: Check if tools list is provided
      run: |
        if [ -z "${{ inputs.tools }}" ]; then
          echo "No tools provided to install."
          exit 1
        fi
      shell: bash

    - name: Install Tools
      run: |
        IFS=$'\n' # Set internal field separator to newline
        for tool_with_version in ${{ inputs.tools }}; do
          tool=$(echo "$tool_with_version" | cut -d':' -f1)
          version=$(echo "$tool_with_version" | cut -d':' -f2-)
          case "$tool" in
            kustomize)
              if [ -z "$version" ]; then
                echo "No input version provided for kustomize. Using default version 5.4.1."
                version="5.4.1"
              fi
              wget -qO /tmp/kustomize.tar.gz "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv${version}/kustomize_v${version}_linux_amd64.tar.gz"
              if [ $? -ne 0 ]; then
                echo "Failed to download kustomize."
                exit 1
              fi
              tar -xvzf /tmp/kustomize.tar.gz -C /tmp/
              if [ $? -ne 0 ]; then
                echo "Failed to extract kustomize."
                exit 1
              fi
              sudo mv /tmp/kustomize /usr/local/bin/
              ;;
            gh)
              # Install gh
              # Script for installing gh
              ;;
            ridectl)
              # Install ridectl
              # Script for installing ridectl
              ;;
            helm)
              # Install helm
              # Script for installing helm
              ;;
            *)
              echo "Unsupported tool: $tool"
              exit 1
              ;;
          esac
        done
      shell: bash
