on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to get image tag
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: ajinkyak423/Tag-name-action@resource-checking
        with:
          file: eu-prod/actiontest.yaml   
