name: Kustomize_test
on:
  push:
  
jobs:
  Kustomize_test:
    name: Kustomize_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install prerequisites
        uses: ajinkyak423/Tag-name-action@kustomization
        with:
          tools: kustomize:3.2.1,ridectl:0.3.2,gh
