on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to get image tag
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: ajinkyak423/tag-name-action
        with:
          images: ajinkyak423
      - run: echo image-tag ${{ steps.foo.outputs.image-tag }}
        shell: bash
      - run: echo image-tag-value ${{ steps.foo.outputs.image-tag-value }}
        shell: bash    
