on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to get image tag
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: ajinkyak423/Tag-name-action@kustomization
        
      - run: echo "${{ steps.foo.outputs.file_path }}"
        shell: bash
      - run: cat ${{ steps.foo.outputs.file_path }}
        shell: bash   