on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: ajinkyak423/Tag-name-action@v1
        with:
          who-to-greet: '1703589266-1289188-ocean-b2i-major-pcr12-21st-dec23MonatheOctocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
