on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: resource-check
    steps:
      - uses: actions/checkout@v4
      - name: Check Dir
        run: |
         pwd
         ls -lah
      - id: foo
        uses: ajinkyak423/Tag-name-action@resource-checking
        with:
          file: kubernetes/test.yaml