on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to get image tag
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: ajinkyak423/Tag-name-action@tag-name-action
        with:
          images: ajinkyak423
          tag-suffix: thi
      - run: echo image-tag ${{ steps.foo.outputs.tag }}
        shell: bash
      - run: echo image-tag-value ${{ steps.foo.outputs.version }}
        shell: bash    
